### ISSUE TITLE
Schedule for the social activities 

### ISSUE THREAD

**Issue by ranti** [code4lib/2021.code4lib.org#160]
Information from Becky for the website: 

Community Gathering - Monday 3/22, 6 pm to 7 pm EDT
Board game night - Tuesday 3/23, 6 pm to 8 pm EDT
Karaoke night - Wednesday 3/24, 6 to 7:30 pm EDT 
Trivia night - Thursday 3/25, 6 to 7:30 pm EDT

Becky can provide blurbs for each night if we would like to have them on the website. 

Sign-up sheets are being worked on and hopefully willl be ready by the end of the month.

**Comment by dzoladz** [comment]
@ranti I just pushed branch `issue#160` to begin this work. Please take a look and provide feedback.

You'll want to review the following pages:
- http://127.0.0.1:4000/schedule/
- http://127.0.0.1:4000/general-info/social/

The following objects were added to `conf.yml`

```
community-gathering:
    show: true
    date: '2021-03-22'
    time: '7PM'
    description: ''
    event-url: ''
    sign-up-url: ''

game-night:
    show: true
    date: '2021-03-23'
    time: '6PM to 8PM'
    description: 'Play games? Come join your fellow code4libers in a few board or card games!'
    event-url: ''
    sign-up-url: ''

karaoke-night:
    show: true
    date: '2021-03-24'
    time: '6PM to 7:30PM'
    description: 'We also have Karaoke night for those who would like to share your passions in singing, or just hangout with friendly folks.'
    event-url: ''
    sign-up-url: ''

trivia-night:
    show: true
    date: '2021-03-25'
    time: '6PM to 7:30PM'
    description: ''
    event-url: ''
    sign-up-url: ''
```
